### ISSUE TITLE
Move sqlparser-rs back into the Apache Arrow DataFusion project?

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-sqlparser-rs#1139]
I started a discussion on the Apache Arrow dev mailing list about possibly moving this project back into DataFusion.

https://lists.apache.org/thread/q80j49poyg99x2c01900312qz7ps9wgp

```
The sqlparser-rs project [1] seems to have become the de-facto SQL parser
for Rust, with almost 4 million downloads so far. This was originally part
of DataFusion very early on, and I moved it into a separate project because
it seemed useful for other projects. This was before DataFusion was known
as a composable query engine, and with hindsight, I probably should have
left it as part of the DataFusion project.

Now that DataFusion has a reputation as a composable query engine, I think
it would make sense to move this code back into DataFusion, where it would
benefit from a larger community of maintainers.

I would like to hear thoughts from the Apache Arrow / DataFusion community.
Does this seem like a good idea?

Thanks,

Andy.

[1] https://github.com/sqlparser-rs/sqlparser-rs
```

**Comment by alamb** [comment]
Here is a related discussion in sqlparser: https://github.com/sqlparser-rs/sqlparser-rs/issues/818

**Comment by max-sixty** [comment]
Hi @andygrove !

Is the proposal to bring the code into a data fusion _crate_? Or just the data fusion repo?

**Comment by andygrove** [comment]
> Is the proposal to bring the code into a data fusion _crate_? Or just the data fusion repo?

My suggestion was simply to move the `sqlparser` crate into the datafusion repo. It would still be the `sqlparser` crate. I would image that this would just become a new top-level `sqlparser` directory in the repo.

**Comment by max-sixty** [comment]
Ah cool! No view in that case. (From a very happy & grateful user, thanks for the library!)

**Comment by alamb** [comment]
We have completed this project -- see https://github.com/apache/datafusion-sqlparser-rs/issues/1294
