### ISSUE TITLE
Add `Display` implementation for other `DML` operations

### ISSUE THREAD

**Issue by seve-martinez** [apache/datafusion-sqlparser-rs#1420]
Much like `Select` and `CreateTable`, the ability to programmatically construct queries from AST parts is incredibly useful.

However, `Insert`, `Delete`, and `Alter` do not implement Display, making it difficult to produce these statements as strings.

**Comment by seve-martinez** [comment]
@alamb happy to take a stab at this if there is no active workstream on it.

**Comment by alamb** [comment]
> @alamb happy to take a stab at this if there is no active workstream on it.

There is none that I know of
