### ISSUE TITLE
support for mssql `json_object` syntax 

### ISSUE THREAD

**Issue by lovasoa** [apache/datafusion-sqlparser-rs#1506]
SQL server has a json_object function with a special syntax that uses colons instead of commas between json keys and values.

```sql
SELECT JSON_OBJECT('name':'value', 'type':1)
```

This is not yet supported in sqlparser. This would be useful in [SQLPage](https://sql-page.com) where we use json for advanced features.

Reference: https://learn.microsoft.com/en-us/sql/t-sql/functions/json-object-transact-sql?view=sql-server-ver16

@gaoqiangz this may be of interest to you :)

**Comment by gaoqiangz** [comment]
👌

**Comment by lovasoa** [comment]
Fixed by @gaoqiangz . Thank you !
