### ISSUE TITLE
MySQL's `CREATE TABLE ... SELECT` syntax

### ISSUE THREAD

**Issue by lovasoa** [apache/datafusion-sqlparser-rs#1509]
SQLite, Postgres, MsSQL and MySQL all support the `CREATE TABLE table_name(columns) AS SELECT ...`.

However, MySQL (and Mariadb) allow omitting the `AS` keyword, and specifying a table like 

```sql
CREATE TABLE bar (m INT) SELECT n FROM foo;
```

Currently, sqlparser parses this as two distinct statements: a create table followed by a select. Instead, it should parse it the same as

```sql
CREATE TABLE bar (m INT) AS SELECT n FROM foo;
```

https://dev.mysql.com/doc/refman/8.4/en/create-table-select.html

**Comment by alamb** [comment]
I believe this is fixed in https://github.com/apache/datafusion-sqlparser-rs/pull/1515
