### ISSUE TITLE
Snowflake COMMENT ON support

### ISSUE THREAD

**Issue by psukys** [apache/datafusion-sqlparser-rs#1511]
Support for https://docs.snowflake.com/en/sql-reference/sql/comment, for example:
```sql
COMMENT ON my_schema.my_table IS 'hello world'
```

Currently, parsing fails:

```
Expected: an SQL statement, found: COMMENT
```

**Comment by git-hulk** [comment]
Hi @psukys

I can submit a PR to resolve this issue if you're planning to do it.

**Comment by psukys** [comment]
@git-hulk please do, I lack knowledge on internals to pick it up immediatelly
