### ISSUE TITLE
Improve the visitor for the `Option` fields

### ISSUE THREAD

**Issue by goldmedal** [apache/datafusion-sqlparser-rs#1568]
https://github.com/apache/datafusion-sqlparser-rs/pull/1556 enables the visitor to visit the `Option` field annotated with `visit(with = "visit_xxx")` in an `Expr`. I focused on implementing the macro and fixing the functionality of `SHOW COLUMNS` in DataFusion.  
However, other fields also need to be annotated. See @alamb's comment (https://github.com/apache/datafusion-sqlparser-rs/pull/1556#discussion_r1862005838) for details.

**Comment by git-hulk** [comment]
@alamb @iffyio Can close this issue since it has been done now.

**Comment by alamb** [comment]
Thanks for the callout @git-hulk
