### ISSUE TITLE
Main branch, linter failure on new Rust version

### ISSUE THREAD

**Issue by demetribu** [apache/datafusion-sqlparser-rs#1569]
It seems the main branch is currently failing Clippy lint checks against Rust 1.83.0. Previous succ run was on stable-x86_64-unknown-linux-gnu unchanged - rustc 1.82.0.

cc @alamb

**Comment by demetribu** [comment]
related #1570

**Comment by alamb** [comment]
Thanks for the report @demetribu  -- hopefully this is fixed now
