### ISSUE TITLE
sqlite analyze don't require a table keyword??

### ISSUE THREAD

**Issue by yuyang-ok** [apache/datafusion-sqlparser-rs#1583]
https://docs.rs/sqlparser/0.52.0/sqlparser/ast/enum.Statement.html#variant.Analyze don't this struct contains the sqlite analyze statement,  and sqlite don't require keywords `table` ,
Is this a bug or ??

**Comment by alamb** [comment]
I am not sure what you are asking here. If a syntax you are looking for is not supported, we would welcome a PR to add support and tests.

**Comment by iffyio** [comment]
Resolved in https://github.com/apache/datafusion-sqlparser-rs/pull/1599

**Comment by alamb** [comment]
🎉
